mklink /D /J 01_FontGenerator       ..\webserver\src\main\webapp\01_FontGenerator
mklink /D /J 02_BackgroundGenerator ..\webserver\src\main\webapp\02_BackgroundGenerator
mklink /D /J 03_GradientGenerator   ..\webserver\src\main\webapp\03_GradientGenerator
mklink /D /J 04_PositionGenerator   ..\webserver\src\main\webapp\04_PositionGenerator
mklink /D /J 05_Column              ..\webserver\src\main\webapp\05_Column
mklink /D /J 06_Menu                ..\webserver\src\main\webapp\06_Menu
mklink /D /J 07_Transform           ..\webserver\src\main\webapp\07_Transform
mklink /D /J 08_Cube                ..\webserver\src\main\webapp\08_Cube
mklink /D /J 09_Transition          ..\webserver\src\main\webapp\09_Transition
mklink /D /J 10_Logo                ..\webserver\src\main\webapp\10_Logo
mklink /D /J 11_Storyboard          ..\webserver\src\main\webapp\11_Storyboard
mklink /D /J CodingTest             ..\webserver\src\main\webapp\CodingTest